version: "3.7"
name: dev-davidsilva-blog
services:
  database:
    container_name: dev-davidsilva-blog-db
    image: mysql:8
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog
    ports:
      # HOST:CONTAINER
      - "3306:3306"
    volumes:
      - type: volume
        source: blog_db_volume
        target: /var/lib/mysql
      - ./database:/database
    command: "--log-bin-trust-function-creators=1 --explicit_defaults_for_timestamp=0 --general-log=1 --general-log-file=/database/mysql.log"
    networks:
      - dev-davidsilva-blog-network
  mysqld-exporter:
    container_name: dev-davidsilva-blog-mysqld-exporter
    image: prom/mysqld-exporter
    environment:
      MYSQLD_EXPORTER_PASSWORD: "rootpassword"
    command:
      - --collect.info_schema.tablestats
      - --mysqld.address=database:3306
      - --mysqld.username=root
    ports:
      - 9104:9104
    depends_on:
      - database
    networks:
      - dev-davidsilva-blog-network
  prometheus:
    image: prom/prometheus
    container_name: dev-davidsilva-blog-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - mysqld-exporter
    networks:
      - dev-davidsilva-blog-network

volumes:
  blog_db_volume:
    external: false
    name: dev-davidsilva-blog-db-volume
  prometheus_data:
    external: false
    name: dev-davidsilva-blog-prometheus-data

networks:
  dev-davidsilva-blog-network:
    driver: bridge
    name: dev-davidsilva-blog-network
